name = "sheet-rag"
compatibility_date = "2026-03-27"
# This property is required for Pages projects to validate the config
pages_build_output_dir = "." 

[[ai_search_namespaces]]
binding = "MY_SEARCH"
namespace = "default"